### ISSUE TITLE
TypeError in _getString() due to change in Node.js Buffer.concat()

### ISSUE THREAD

**Issue by kixxauth** [lykmapipo/mock-express-response#3]
Stack trace:

```
TypeError: "list" argument must be an Array of Buffers
        at Function.Buffer.concat (buffer.js:313:11)
        at MockExpressResponse.MockServerResponse._getString (/home/travis/build/oddnetworks/oddworks/node_modules/mock-res/index.js:55:16)
        at MockExpressResponse.MockServerResponse._getJSON (/home/travis/build/oddnetworks/oddworks/node_modules/mock-res/index.js:59:25)
```

Submitted to mock-res for reference: https://github.com/diachedelic/mock-res/issues/5

**Comment by jakubholynet** [comment]
So the solution is to upgrade the dependency on mock-rest v0.3.3+ that fixes it, right?
